### ISSUE TITLE
Install Erro

### ISSUE THREAD

**Issue by GrapeFruitWolfs** [antfu/vitesse-lite#17]
Sorry waste u time, but i encountered a problem.
I `degit antfu/vitesse-lite` And  executed command  `pnpm i` they smooth operation.
when i execut `pnpm dev` Error prompt it
```

D:\VUE\demo\vue-minesweeper>pnpm dev

> @ dev D:\VUE\demo\vue-minesweeper
> vite --port 3333 --open

failed to load config from D:\VUE\demo\vue-minesweeper\vite.config.ts
error when starting dev server:
D:\VUE\demo\vue-minesweeper\node_modules\.pnpm\@unocss+vite@0.33.2_vite@2.9.8\node_modules\@unocss\vite\dist\index.cjs:284
        return command === "build" && !options.build?.ssr;
                                                     ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\VUE\demo\vue-minesweeper\node_modules\.pnpm\unocss@0.33.2_vite@2.9.8\node_modules\unocss\dist\vite.cjs:5:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
 ELIFECYCLE  Command failed with exit code 1.
```

Can you tell me any solution and what caused this problem ,Thanks.

**Comment by antfu** [comment]
Please use the latest version of Node

**Comment by GrapeFruitWolfs** [comment]
> Please use the latest version of Node
感激不尽 谢谢安东尼老师.
