### ISSUE TITLE
Error on install 

### ISSUE THREAD

**Issue by travbus** [antfu/vitesse-lite#9]
PLEASE READ: I originally made this template for myself to mocking up apps quicker. I am glad to see you are willing to give it a try! Before your open the issue, please make sure you are reporting bugs in the template itself. **I am NOT creating this template to solve the problems you faced in your project, please use Vue or Vite's discord server to ask questions.** Thank you.

**Describe the bug/issue**

I cloned this git ran npm i to install node modules ran npm run dev and i get an error. Any ideas? 

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Traviss-MacBook-Pro:vitesse-lite travisklein$ npm run dev

> @ dev /Users/travisklein/Dropbox/vueApps/test/vitesse-lite
> vite --port 3333 --open

failed to load config from /Users/travisklein/Dropbox/vueApps/test/vitesse-lite/vite.config.ts
error when starting dev server:
/Users/travisklein/Dropbox/vueApps/test/vitesse-lite/node_modules/.pnpm/@unocss+core@0.23.0/node_modules/@unocss/core/dist/index.cjs:188
    return this._map.get(key1)?.has(key2);
                               ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/travisklein/Dropbox/vueApps/test/vitesse-lite/node_modules/.pnpm/unocss@0.23.0_jsdom@19.0.0/node_modules/unocss/dist/index.cjs:5:14)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `vite --port 3333 --open`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/travisklein/.npm/_logs/2022-02-10T20_47_49_375Z-debug.log

debug info
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@6.14.8
3 info using node@v12.19.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @~predev: @
6 info lifecycle @~dev: @
7 verbose lifecycle @~dev: unsafe-perm in lifecycle true
8 verbose lifecycle @~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/travisklein/Dropbox/vueApps/test/vitesse-lite/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle @~dev: CWD: /Users/travisklein/Dropbox/vueApps/test/vitesse-lite
10 silly lifecycle @~dev: Args: [ '-c', 'vite --port 3333 --open' ]
11 silly lifecycle @~dev: Returned: code: 1  signal: null
12 info lifecycle @~dev: Failed to exec dev script
13 verbose stack Error: @ dev: `vite --port 3333 --open`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid @
15 verbose cwd /Users/travisklein/Dropbox/vueApps/test/vitesse-lite
16 verbose Darwin 20.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v12.19.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error @ dev: `vite --port 3333 --open`
22 error Exit status 1
23 error Failed at the @ dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by travbus** [comment]
I figured it out
